-- Where's the News? PostgreSQL schema for Supabase
-- Run this in Supabase SQL Editor or via Supabase migrations.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  username text not null unique,
  username_lower text generated always as (lower(username)) stored unique,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_headlines (
  id bigint generated by default as identity primary key,
  source_name text,
  source_url text,
  original_title text not null,
  summarized_clue text not null,
  event_date date,
  city text,
  region text,
  country text,
  latitude double precision,
  longitude double precision,
  is_historical boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.guesses (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  headline_id bigint not null references public.daily_headlines(id) on delete cascade,
  guessed_latitude double precision not null,
  guessed_longitude double precision not null,
  distance_km double precision,
  stage_score integer,
  created_at timestamptz not null default now()
);

create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  game_mode text not null check (game_mode in ('historical', 'current', 'default')),
  total_score integer not null default 0,
  stages_completed integer not null default 0,
  completed_at timestamptz not null default now()
);

create or replace view public.leaderboard as
select
  p.id as user_id,
  p.username,
  max(s.total_score) as best_score,
  count(s.id) as games_played
from public.profiles p
join public.scores s on s.user_id = p.id
where s.stages_completed = 5
group by p.id, p.username;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, username)
  values (
    new.id,
    new.email,
    coalesce(nullif(new.raw_user_meta_data->>'username', ''), split_part(new.email, '@', 1))
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.daily_headlines enable row level security;
alter table public.guesses enable row level security;
alter table public.scores enable row level security;

create policy "Users read own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users update own profile" on public.profiles for update using (auth.uid() = id);
create policy "Headlines are readable" on public.daily_headlines for select using (true);
create policy "Users read own guesses" on public.guesses for select using (auth.uid() = user_id);
create policy "Users insert own guesses" on public.guesses for insert with check (auth.uid() = user_id);
create policy "Users read own scores" on public.scores for select using (auth.uid() = user_id);
create policy "Users insert own scores" on public.scores for insert with check (auth.uid() = user_id);
